# Generated by Django 5.1.4 on 2026-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_document_project_approval_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_nonce',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
